<?php

return [
    'signs' => [
        'aries' => [
            'name' => 'Aries',
            'dates' => 'Mar 21 - Apr 19',
            'months' => [3 => range(21, 31), 4 => range(1, 19)],
            'description' => 'Bold, ambitious, and a natural leader.',
            'pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/main/rpt_Aries_CLP_K3mL9xP2Qa8Tv7Rx.pdf',
            'bundle_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/main/bundle/bnd_Aries_CLP_K3mL9xP2Qa7Tv8Rx.zip',
            'vip_url' => 'https://thecosmiclifepath.com/download/aries',
            'standard_url' => 'https://thecosmiclifepath.com/download/aries',
            'vip_purchase_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-aries47&template=BCoFTclp&cbfid=63364&vtid=cta1',
            'standard_purchase_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-aries15&template=BCoFTclp&cbfid=63364&vtid=cta1',
            'special_offer_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-aries15&template=BCoFTclp&cbfid=63364&vtid=ariesdl',
            
            'upsell1_accept_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto1-aries67&cbur=a',
            'upsell1_decline_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto1-aries67&cbur=d',
            'upsell2_accept_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto2-aries47&cbur=a',
            'upsell2_decline_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto2-aries47&cbur=d',

            'upsell1_bundle_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/cosmic-wealth-path/Bundle/bnd_Aries_WB_Q3mL9xP2Ka8Rv7T.zip',
            'upsell1_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/cosmic-wealth-path/rpt_Aries_Q7mL9xP2Ka8N.pdf',
            'upsell2_bundle_pdf' => '',
            'upsell2_pdf' => '',
            'upsell3_pdf' => '',
        ],
        'taurus' => [
            'name' => 'Taurus',
            'months' => [4 => range(20, 30), 5 => range(1, 20)],
            'dates' => 'Apr 20 - May 20',
            'description' => 'Grounded, reliable, and values comfort.',
            'pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/main/rpt_Taurus_CLP_M4vX8qL1Rp6Dc2Yw.pdf',
            'bundle_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/main/bundle/bnd_Taurus_CLP_M4vX8qL1Rp6Dc2Yw.zip',
            'vip_url' => 'https://thecosmiclifepath.com/download/taurus',
            'standard_url' => 'https://thecosmiclifepath.com/download/taurus',

            'vip_purchase_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-taurus47&template=BCoFTclp&cbfid=63372&vtid=cta1',
            'standard_purchase_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-taurus15&template=BCoFTclp&cbfid=63372&vtid=cta1',
            'special_offer_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-taurus15&template=BCoFTclp&cbfid=63372&vtid=taurusdl',
            
            'upsell1_accept_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto1-taurus67&cbur=a',
            'upsell1_decline_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto1-taurus67&cbur=d',
            'upsell2_accept_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto2-taurus47&cbur=a',
            'upsell2_decline_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto2-taurus47&cbur=d',

            'upsell1_bundle_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/cosmic-wealth-path/Bundle/bnd_Taurus_WB_M4vX8qL1Rp6Dc2Y.zip',
            'upsell1_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/cosmic-wealth-path/rpt_Taurus_M4vX8qL1Rp6D.pdf',
            'upsell2_bundle_pdf' => '',
            'upsell2_pdf' => '',
            'upsell3_pdf' => '',
        ],
        'gemini' => [
            'name' => 'Gemini',
            'dates' => 'May 21 - Jun 20',
            'months' => [5 => range(21, 31), 6 => range(1, 20)],
            'description' => 'Curious, adaptable, and a great communicator.',
            'pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/main/rpt_Gemini_CLP_Z4kP3wN7Tx2Bm9Ls.pdf',
            'bundle_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/main/bundle/bnd_Gemini_CLP_Z4kP3wN7Tx2Bm9Ls.zip',
            'vip_url' => 'https://thecosmiclifepath.com/download/gemini',
            'standard_url' => 'https://thecosmiclifepath.com/download/gemini',
            'vip_purchase_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-gemini47&template=BCoFTclp&cbfid=63366&vtid=cta1',
            'standard_purchase_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-gemini15&template=BCoFTclp&cbfid=63366&vtid=cta1',
            'special_offer_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-gemini15&template=BCoFTclp&cbfid=63366&vtid=geminidl',
            
            'upsell1_accept_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto1-gemini67&cbur=a',
            'upsell1_decline_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto1-gemini67&cbur=d',
            'upsell2_accept_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto2-gemini47&cbur=a',
            'upsell2_decline_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto2-gemini47&cbur=d',

            'upsell1_bundle_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/cosmic-wealth-path/Bundle/bnd_Gemini_WB_Z4kP3wN7Tx2Bm9L.zip',
            'upsell1_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/cosmic-wealth-path/rpt_Gemini_Z9kP3wN7Tx2B.pdf',
            'upsell2_bundle_pdf' => '',
            'upsell2_pdf' => '',
            'upsell3_pdf' => '',
        ],
        'cancer' => [
            'name' => 'Cancer',
            'dates' => 'Jun 21 - Jul 22',
            'months' => [6 => range(21, 30), 7 => range(1, 22)],
            'description' => 'Intuitive, caring, and deeply loyal.',
            'pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/main/rpt_Cancer_CLP_H5qV8mL1Yp7Rw4Kd.pdf',
            'bundle_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/main/bundle/bnd_Cancer_CLP_H5qV8mL1Yp4Rw7Kd.zip',
            'vip_url' => 'https://thecosmiclifepath.com/download/cancer',
            'standard_url' => 'https://thecosmiclifepath.com/download/cancer',
            'vip_purchase_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-cancer47&template=BCoFTclp&cbfid=63362&vtid=cta1',
            'standard_purchase_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-cancer15&template=BCoFTclp&cbfid=63362&vtid=cta1',
            'special_offer_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-cancer15&template=BCoFTclp&cbfid=63362&vtid=cancerdl',
            
            'upsell1_accept_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto1-cancer67&cbur=a',
            'upsell1_decline_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto1-cancer67&cbur=d',
            'upsell2_accept_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto2-cancer47&cbur=a',
            'upsell2_decline_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto2-cancer47&cbur=d',

            'upsell1_bundle_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/cosmic-wealth-path/Bundle/bnd_Cancer_WB_H5qV8mL1Yp7Rx3K.zip',
            'upsell1_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/cosmic-wealth-path/rpt_Cancer_H2qV8mL5Yp1R.pdf',
            'upsell2_bundle_pdf' => '',
            'upsell2_pdf' => '',
            'upsell3_pdf' => '',
        ],
        'leo' => [
            'name' => 'Leo',
            'dates' => 'Jul 23 - Aug 22',
            'months' => [7 => range(23, 31), 8 => range(1, 22)],
            'description' => 'Confident, creative, and loves the spotlight.',
            'pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/main/rpt_Leo_CLP_X6nK2pQ9Lm4Tr8Vq.pdf',
            'bundle_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/main/bundle/bnd_Leo_CLP_X6nK2pQ9Lm4Tr8Vq.zip',
            'vip_url' => 'https://thecosmiclifepath.com/download/cancer',
            'standard_url' => 'https://thecosmiclifepath.com/download/cancer',
            'vip_purchase_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-leo47&template=BCoFTclp&cbfid=63367&vtid=cta1',
            'standard_purchase_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-leo15&template=BCoFTclp&cbfid=63367&vtid=cta1',
            'special_offer_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-leo15&template=BCoFTclp&cbfid=63367&vtid=leodl',
            
            'upsell1_accept_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto1-leo67&cbur=a',
            'upsell1_decline_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto1-leo67&cbur=d',
            'upsell2_accept_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto2-leo47&cbur=a',
            'upsell2_decline_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto2-leo47&cbur=d',

            'upsell1_bundle_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/cosmic-wealth-path/Bundle/bnd_Leo_WB_X6nK2pQ9Lm4Tr8V.zip',
            'upsell1_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/cosmic-wealth-path/rpt_Leo_X6nK2pQ9Lm4T.pdf',
            'upsell2_bundle_pdf' => '',
            'upsell2_pdf' => '',
            'upsell3_pdf' => '',
        ],
        'virgo' => [
            'name' => 'Virgo',
            'dates' => 'Aug 23 - Sep 22',
            'months' => [8 => range(22, 31), 9 => range(1, 22)],
            'description' => 'Analytical, practical, and detail-oriented.',
            'pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/main/rpt_Virgo_CLP_P8wR3xM6Qa1Jt9Xn.pdf',
            'bundle_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/main/bundle/bnd_Virgo_CLP_P8wR3xM6Qa1Jt9Xn.zip',
            'vip_url' => 'https://thecosmiclifepath.com/download/cancer',
            'standard_url' => 'https://thecosmiclifepath.com/download/cancer',
            'vip_purchase_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-virgo47&template=BCoFTclp&cbfid=63373&vtid=cta1',
            'standard_purchase_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-virgo15&template=BCoFTclp&cbfid=63373&vtid=cta1',
            'special_offer_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-virgo15&template=BCoFTclp&cbfid=63373&vtid=virgodl',
            
            'upsell1_accept_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto1-virgo67&cbur=a',
            'upsell1_decline_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto1-virgo67&cbur=d',
            'upsell2_accept_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto2-virgo47&cbur=a',
            'upsell2_decline_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto2-virgo47&cbur=d',

            'upsell1_bundle_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/cosmic-wealth-path/Bundle/bnd_Virgo_WB_P8wR3xM6Qa1Jt9X.zip',
            'upsell1_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/cosmic-wealth-path/rpt_Virgo_P8wR3xM6Qa1J.pdf',
            'upsell2_bundle_pdf' => '',
            'upsell2_pdf' => '',
            'upsell3_pdf' => '',
        ],
        'libra' => [
            'name' => 'Libra',
            'dates' => 'Sep 23 - Oct 22',
            'months' => [9 => range(23, 30), 10 => range(1, 22)],
            'description' => 'Diplomatic, fair-minded, and social.',
            'pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/main/rpt_Libra_CLP_T5mZ9qK2Xp7Nw4Rc.pdf',
            'bundle_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/main/bundle/bnd_Libra_CLP_T5mZ9qK2Xp7Nw4Rc.zip',
            'vip_url' => 'https://thecosmiclifepath.com/download/cancer',
            'standard_url' => 'https://thecosmiclifepath.com/download/cancer',
            'vip_purchase_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-libra47&template=BCoFTclp&cbfid=63368&vtid=cta1',
            'standard_purchase_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-libra15&template=BCoFTclp&cbfid=63368&vtid=cta1',
            'special_offer_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-libra15&template=BCoFTclp&cbfid=63368&vtid=libradl',
            
            'upsell1_accept_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto1-libra67&cbur=a',
            'upsell1_decline_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto1-libra67&cbur=d',
            'upsell2_accept_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto2-libra47&cbur=a',
            'upsell2_decline_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto2-libra47&cbur=d',

            'upsell1_bundle_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/cosmic-wealth-path/Bundle/bnd_Libra_WB_T5mZ9qK2Xp7Nw4R.zip',
            'upsell1_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/cosmic-wealth-path/rpt_Libra_T5mZ9qK2Xp7N.pdf',
            'upsell2_bundle_pdf' => '',
            'upsell2_pdf' => '',
            'upsell3_pdf' => '',
        ],
        'scorpio' => [
            'name' => 'Scorpio',
            'dates' => 'Oct 23 - Nov 21',
            'months' => [10 => range(23, 31), 11 => range(1, 21)],
            'description' => 'Passionate, resourceful, and determined.',
            'pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/main/rpt_Scorpio_CLP_R1xV7pL4Km9Qz5Tf.pdf',
            'bundle_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/main/bundle/bnd_Scorpio_CLP_R1xV7pL4Km9Qz5Tf.zip',
            'vip_url' => 'https://thecosmiclifepath.com/download/cancer',
            'standard_url' => 'https://thecosmiclifepath.com/download/cancer',
            'vip_purchase_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-scorpio47&template=BCoFTclp&cbfid=63371&vtid=cta1',
            'standard_purchase_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-scorpio15&template=BCoFTclp&cbfid=63371&vtid=cta1',
            'special_offer_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-scorpio15&template=BCoFTclp&cbfid=63371&vtid=scorpiodl',
            
            'upsell1_accept_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto1-scorpio67&cbur=a',
            'upsell1_decline_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto1-scorpio67&cbur=d',
            'upsell2_accept_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto2-scorpio47&cbur=a',
            'upsell2_decline_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto2-scorpio47&cbur=d',

            'upsell1_bundle_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/cosmic-wealth-path/Bundle/bnd_Scorpio_WB_R1xV7pL4Km9Qz5T.zip',
            'upsell1_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/cosmic-wealth-path/rpt_Scorpio_R1xV7pL4Km9Q.pdf',
            'upsell2_bundle_pdf' => '',
            'upsell2_pdf' => '',
            'upsell3_pdf' => '',
        ],
        'sagittarius' => [
            'name' => 'Sagittarius',
            'dates' => 'Nov 22 - Dec 21',
            'months' => [11 => range(22, 30), 12 => range(1, 21)],
            'description' => 'Adventurous, optimistic, and philosophical.',
            'pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/main/rpt_Sagittarius_CLP_N3qP8mX5Lv2Kh7Qd.pdf',
            'bundle_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/main/bundle/bnd_Sagittarius_CLP_N3qP8mX5Lv2Kh7Qd.zip',
            'vip_url' => 'https://thecosmiclifepath.com/download/cancer',
            'standard_url' => 'https://thecosmiclifepath.com/download/cancer',
            'vip_purchase_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-sagit47&template=BCoFTclp&cbfid=63370&vtid=cta1',
            'standard_purchase_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-sagit15&template=BCoFTclp&cbfid=63370&vtid=cta1',
            'special_offer_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-sagit15&template=BCoFTclp&cbfid=63370&vtid=sagittariusdl',
            
            'upsell1_accept_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto1-sagit67&cbur=a',
            'upsell1_decline_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto1-sagit67&cbur=d',
            'upsell2_accept_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto2-sagit47&cbur=a',
            'upsell2_decline_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto2-sagit47&cbur=d',

            'upsell1_bundle_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/cosmic-wealth-path/Bundle/bnd_Sagittarius_WB_N3qP8mX5Lv2Kh7Q.zip',
            'upsell1_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/cosmic-wealth-path/rpt_Sagittarius_N3qP8mX5Lv2K.pdf',
            'upsell2_bundle_pdf' => '',
            'upsell2_pdf' => '',
            'upsell3_pdf' => '',
        ],
        'capricorn' => [
            'name' => 'Capricorn',
            'dates' => 'Dec 22 - Jan 19',
            'months' => [12 => range(22, 31), 1 => range(1, 19)],
            'description' => 'Disciplined, ambitious, and responsible.',
            'pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/main/rpt_Capricorn_CLP_Y2kM7xQ9Rp4Tn8Vz.pdf',
            'bundle_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/main/bundle/bnd_Capricorn_CLP_Y2kM7xQ9Rp4Tn8Vz.zip',
            'vip_url' => 'https://thecosmiclifepath.com/download/cancer',
            'standard_url' => 'https://thecosmiclifepath.com/download/cancer',
            'vip_purchase_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-capri47&template=BCoFTclp&cbfid=63365&vtid=cta1',
            'standard_purchase_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-capri15&template=BCoFTclp&cbfid=63365&vtid=cta1',
            'special_offer_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-capri15&template=BCoFTclp&cbfid=63365&vtid=capricorndl',
            
            'upsell1_accept_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto1-capri67&cbur=a',
            'upsell1_decline_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto1-capri67&cbur=d',
            'upsell2_accept_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto2-capri47&cbur=a',
            'upsell2_decline_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto2-capri47&cbur=d',

            'upsell1_bundle_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/cosmic-wealth-path/Bundle/bnd_Capricorn_WB_Y2kM7xQ9Rp4Tv8N.zip',
            'upsell1_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/cosmic-wealth-path/rpt_Capricorn_Y7kM1xQ9Rp4T.pdf',
            'upsell2_bundle_pdf' => '',
            'upsell2_pdf' => '',
            'upsell3_pdf' => '',
        ],
        'aquarius' => [
            'name' => 'Aquarius',
            'dates' => 'Jan 20 - Feb 18',
            'months' => [1 => range(20, 31), 2 => range(1, 18)],
            'description' => 'Innovative, independent, and humanitarian.',
            'pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/main/rpt_Aquarius_CLP_F8kQ2mX7Lp9Rv3Na.pdf',
            'bundle_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/main/bundle/bnd_Aquarius_CLP_F9kQ2mX7Lp4Rv8Na.zip',

            'vip_url' => 'https://thecosmiclifepath.com/download/cancer',
            'standard_url' => 'https://thecosmiclifepath.com/download/cancer',

            'vip_purchase_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-aqua47&template=BCoFTclp&cbfid=63363&vtid=cta1',
            'standard_purchase_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-aqua15&template=BCoFTclp&cbfid=63363&vtid=cta1',
            'special_offer_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-aqua15&template=BCoFTclp&cbfid=63363&vtid=aquariusdl',

            'upsell1_accept_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto1-aqua67&cbur=a',
            'upsell1_decline_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto1-aqua67&cbur=d',
            'upsell2_accept_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto2-aqua47&cbur=a',
            'upsell2_decline_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto2-aqua47&cbur=d',

            'upsell1_bundle_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/cosmic-wealth-path/Bundle/bnd_Aquarius_WB_L8qX2mP7Rv4Ka9N.zip',
            'upsell1_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/cosmic-wealth-path/rpt_Aquarius_L4pN8qX2Km6R.pdf',
            'upsell2_bundle_pdf' => '',
            'upsell2_pdf' => '',
            'upsell3_pdf' => '',
        ],
        'pisces' => [
            'name' => 'Pisces',
            'dates' => 'Feb 19 - Mar 20',
            'months' => [2 => range(19, 29), 3 => range(1, 20)],
            'description' => 'Empathetic, artistic, and deeply intuitive.',
            'pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/main/rpt_Pisces_CLP_K9xT3mP7Qv1Ls6Mh.pdf',
            'bundle_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/main/bundle/bnd_Pisces_CLP_K9xT3mP7Qv1Ls6Mh.zip',
            'vip_url' => 'https://thecosmiclifepath.com/download/cancer',
            'standard_url' => 'https://thecosmiclifepath.com/download/cancer',
            'vip_purchase_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-pisces47&template=BCoFTclp&cbfid=63369&vtid=cta1',
            'standard_purchase_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-pisces15&template=BCoFTclp&cbfid=63369&vtid=cta1',
            'special_offer_url' => 'https://clifepath.pay.clickbank.net/?cbitems=fe-pisces15&template=BCoFTclp&cbfid=63369&vtid=piscesdl',
            
            'upsell1_accept_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto1-pisces67&cbur=a',
            'upsell1_decline_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto1-pisces67&cbur=d',
            'upsell2_accept_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto2-pisces47&cbur=a',
            'upsell2_decline_cta_url' => 'https://clifepath.pay.clickbank.net/?cbitems=oto2-pisces47&cbur=d',

            'upsell1_bundle_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/cosmic-wealth-path/Bundle/bnd_Pisces_WB_K9xT3mP7Qv1Ls6M.zip',
            'upsell1_pdf' => 'https://cosmic-life-path.nyc3.digitaloceanspaces.com/cosmic-wealth-path/rpt_Pisces_K9xT3mP7Qv1L.pdf',
            'upsell2_bundle_pdf' => '',
            'upsell2_pdf' => '',
            'upsell3_pdf' => '',
        ],
    ],
];
